apiVersion: v1
kind: Pod
metadata:
    name: kuard
spec:
    containers:
        - image: gcr.io/kuard-demo/kuard-arm64:blue
          name: kuard
          ports:
              - containerPort: 8080
                name: http
                protocol: TCP
