apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard-app
  labels:
    app: kuard-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: kuard-app
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kuard-app
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-arm64:blue
        name: kuard
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
