apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          # image: quay.io/external_storage/nfs-client-provisioner-arm:latest
          image: quay.io/external_storage/nfs-subdir-external-provisioner-arm:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: rpi-nfs/vol1
            - name: NFS_SERVER
              value: 192.168.127.11
            - name: NFS_PATH
              value: /mnt/disk/vol1/k8s_nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.127.11
            path: /mnt/disk/vol1/k8s_nfs
