apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: managed-nfs-storage
  nfs:
    server: 192.168.127.8
    path: "/mnt/disk/vol1/registry"
